import type { ExpressionSpecification, StyleSpecification } from 'maplibre-gl';

// Self-contained MapLibre style — no tile server, no network.
// GeoJSON is generated by `npm run gen:basemap` from Natural Earth
// (public domain) and shipped in public/geo/.
//
// Deliberately contains no `glyphs` URL and no symbol layers: glyph PBFs
// would need a server (and a CJK set would be megabytes). All map text is
// rendered as an HTML overlay instead — see GlobeMap.

const base = (import.meta as unknown as { env?: { BASE_URL?: string } }).env?.BASE_URL ?? '/';

const LAND_TINTS: [number, string][] = [
  [0, '#efe3c2'],
  [1, '#f3e9cd'],
  [2, '#ecdfb8'],
  [3, '#f0e5c7'],
];

export const OFFLINE_STYLE: StyleSpecification = {
  version: 8,
  sources: {
    countries: { type: 'geojson', data: `${base}geo/countries.json` },
    graticule: { type: 'geojson', data: `${base}geo/graticule.json` },
    rivers: { type: 'geojson', data: `${base}geo/rivers.json` },
    lakes: { type: 'geojson', data: `${base}geo/lakes.json` },
    cities: { type: 'geojson', data: `${base}geo/cities.json` },
    'country-labels': { type: 'geojson', data: `${base}geo/country-labels.json` },
    admin1: { type: 'geojson', data: `${base}geo/admin1.json` },
    'admin1-labels': { type: 'geojson', data: `${base}geo/admin1-labels.json` },
    roads: { type: 'geojson', data: `${base}geo/roads.json` },
    'physical-labels': { type: 'geojson', data: `${base}geo/physical-labels.json` },
    'river-labels': { type: 'geojson', data: `${base}geo/river-labels.json` },
    // Local static XYZ tile pyramid (public/geo/relief/), generated by
    // `npm run gen:relief` — no tile server, same as every other source here.
    relief: {
      type: 'raster',
      tiles: [`${base}geo/relief/{z}/{x}/{y}.jpg`],
      tileSize: 256,
      minzoom: 0,
      maxzoom: 3,
    },
  },
  sky: {
    'sky-color': '#0b1830',
    'horizon-color': '#3f6a86',
    'fog-color': '#7fa4b0',
    'fog-ground-blend': 0.6,
    'horizon-fog-blend': 0.6,
    'sky-horizon-blend': 0.8,
    'atmosphere-blend': 0.8,
  },
  layers: [
    { id: 'ocean', type: 'background', paint: { 'background-color': '#5f8ea0' } },
    {
      id: 'land',
      type: 'fill',
      source: 'countries',
      paint: {
        'fill-color': [
          'match',
          ['get', 'tint'],
          ...LAND_TINTS.flatMap(([t, c]) => [t, c]),
          '#efe3c2',
        ] as unknown as ExpressionSpecification,
        'fill-opacity': 1,
      },
    },
    // Subtle terrain-shading texture over the flat land tint. Low opacity —
    // it's meant to read as paper grain/relief, not a physical map.
    {
      id: 'relief',
      type: 'raster',
      source: 'relief',
      paint: { 'raster-opacity': 0.32, 'raster-fade-duration': 0 },
    },
    {
      id: 'lakes',
      type: 'fill',
      source: 'lakes',
      paint: { 'fill-color': '#5f92a6', 'fill-opacity': 0.92 },
    },
    {
      id: 'rivers',
      type: 'line',
      source: 'rivers',
      paint: {
        'line-color': '#4a7f94',
        'line-width': ['interpolate', ['linear'], ['zoom'], 1, 0.7, 3, 1.4, 5, 2.2],
        'line-opacity': 0.85,
      },
    },
    {
      id: 'graticule',
      type: 'line',
      source: 'graticule',
      paint: { 'line-color': '#436273', 'line-width': 0.45, 'line-opacity': 0.28 },
    },
    {
      id: 'borders',
      type: 'line',
      source: 'countries',
      paint: { 'line-color': '#8a6840', 'line-width': 0.75, 'line-opacity': 0.75 },
    },
    // State/province boundaries — only worth rendering once zoomed well past
    // whole-country view, else they clutter the globe with noise.
    {
      id: 'admin1-borders',
      type: 'line',
      source: 'admin1',
      minzoom: 3,
      paint: {
        'line-color': '#8a6840',
        'line-width': 0.4,
        'line-opacity': 0.35,
        'line-dasharray': [1, 1.5],
      },
    },
    // Major highways only — texture for zoomed-in views, not a routable network.
    {
      id: 'roads',
      type: 'line',
      source: 'roads',
      minzoom: 3.5,
      paint: {
        'line-color': '#8a6840',
        'line-width': ['interpolate', ['linear'], ['zoom'], 3.5, 0.4, 7, 1.1],
        'line-opacity': 0.4,
      },
    },
    {
      id: 'cities',
      type: 'circle',
      source: 'cities',
      minzoom: 2.2,
      paint: {
        'circle-radius': ['interpolate', ['linear'], ['zoom'], 2, 1.6, 4, 2.8, 6, 3.5],
        'circle-color': '#4a3a28',
        'circle-opacity': 0.75,
        'circle-stroke-width': 0.7,
        'circle-stroke-color': '#fffdf6',
      },
    },
    // Invisible points used only for HTML country-name overlays (no glyphs).
    {
      id: 'country-label-pts',
      type: 'circle',
      source: 'country-labels',
      maxzoom: 3.4,
      paint: { 'circle-radius': 1, 'circle-opacity': 0 },
    },
    // Invisible points used only for HTML state/province-name overlays.
    {
      id: 'admin1-label-pts',
      type: 'circle',
      source: 'admin1-labels',
      minzoom: 3,
      paint: { 'circle-radius': 1, 'circle-opacity': 0 },
    },
    // Invisible points used only for HTML physical-feature-name overlays.
    {
      id: 'physical-label-pts',
      type: 'circle',
      source: 'physical-labels',
      minzoom: 2,
      paint: { 'circle-radius': 1, 'circle-opacity': 0 },
    },
    // Invisible points used only for HTML river-name overlays.
    {
      id: 'river-label-pts',
      type: 'circle',
      source: 'river-labels',
      minzoom: 2,
      paint: { 'circle-radius': 1, 'circle-opacity': 0 },
    },
  ],
};
